SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOOT_COOLDOWN = 0.3 # seconds
PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5

# Scoring constants
SCORE_LARGE_ASTEROID = 100    # For largest asteroids (radius = ASTEROID_MIN_RADIUS * 3)
SCORE_MEDIUM_ASTEROID = 150   # For medium asteroids (radius = ASTEROID_MIN_RADIUS * 2)
SCORE_SMALL_ASTEROID = 200    # For smallest asteroids (radius = ASTEROID_MIN_RADIUS)